name: Upload Python Package

on:
  push:
    branches: [ "main" ]

jobs:
  release-build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Install Deps
        run: |
          pip install -r requirements.txt

      - name: Build and publish
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.TOKEN }}
        run: |
          maturin build --release
          twine upload target/wheels/*
